# Generated by Django 3.0.1 on 2020-01-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/machines/'),
        ),
    ]
