# Generated by Django 3.0.1 on 2020-01-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine_image'),
        ('reservation', '0002_auto_20200127_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='typeReservation',
            field=models.ManyToManyField(to='reservation.TypeReservation'),
        ),
    ]
