# Generated by Django 3.0.1 on 2020-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_typereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='context_with_badge',
            field=models.CharField(default="Qu'est-ce qui affiche avec le formulaire si la personne a la badge", max_length=120),
        ),
        migrations.AddField(
            model_name='machine',
            name='context_without_badge',
            field=models.CharField(default="Qu'est-ce qui affiche avec le formulaire si la personne n'a pas la badge", max_length=120),
        ),
    ]
