# Generated by Django 3.0.1 on 2020-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20200128_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='price',
        ),
        migrations.AddField(
            model_name='machine',
            name='member_price',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='machine',
            name='no_member_price',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
