# Generated by Django 3.0.1 on 2021-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_auto_20200223_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='number_machine',
            field=models.IntegerField(default=1),
        ),
    ]
