# Generated by Django 3.0.1 on 2021-06-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_machine_number_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
