version: '3.7'

services:
  web:
    build:
        context : ./
        dockerfile: Dockerfile.prod
    command: gunicorn FabLab.wsgi:application --bind 0.0.0.0:8000
    volumes:
     - static_volume:/home/FabLab-reservation/web/staticfiles
     - media_volume:/home/FabLab-reservation/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/FabLab-reservation/web/staticfiles
      - media_volume:/home/FabLab-reservation/web/mediafiles
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: