# Generated by Django 3.0.1 on 2021-04-22 00:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='vacation',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(null=True), size=None), size=None),
        ),
    ]
