# Generated by Django 3.0.1 on 2021-04-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210421_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='vacation',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='vacation',
            field=models.ManyToManyField(blank=True, to='accounts.Vacation'),
        ),
    ]
