# Generated by Django 3.0.1 on 2021-04-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210422_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='vacation',
        ),
        migrations.DeleteModel(
            name='Vacation',
        ),
    ]
