# Generated by Django 3.0.1 on 2020-01-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badges',
            name='good_with_machine',
        ),
        migrations.AddField(
            model_name='badges',
            name='name',
            field=models.CharField(default='default', max_length=90),
        ),
    ]
