# Generated by Django 3.0.1 on 2020-02-02 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200128_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typereservation',
            name='max_duration',
        ),
        migrations.RemoveField(
            model_name='typereservation',
            name='min_duration',
        ),
        migrations.AddField(
            model_name='typereservation',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
