# Generated by Django 3.0.1 on 2020-02-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_reservation_typereservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='typeReservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='typeReservation',
            field=models.CharField(default='Formation', max_length=120),
        ),
    ]
