# Generated by Django 3.0.1 on 2020-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20200224_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='badge_picture',
            field=models.ImageField(blank=True, upload_to='photos/badges'),
        ),
    ]
