# Generated by Django 3.0.1 on 2021-04-23 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210422_2011'),
        ('reservation', '0011_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.StaffProfile'),
        ),
    ]
